version: '3'
services:
  #  vend:
  #    container_name: vend
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    ports:
  #      - '8080:8080'
  #    environment:
  #      API_PORT: '8080'
  #      SQL_HOST: 'pg_vend_db'
  #      SQL_PORT: '5432'

  pg_vend_db:
    container_name: pg_vend_db
    build:
      context: .
      dockerfile: database/Dockerfile
    ports:
      - '5432:5432'
    # uncomment for logs
    command: [ 'postgres', '-c', 'log_statement=all' ]
    environment:
      POSTGRES_USER: 'master1'
      POSTGRES_PASSWORD: 'kermit'
      POSTGRES_DB: 'vend'
