version: '3'
services:
  db:
    container_name: vend
    build: ./database
    ports:
      - '5432:5432'
    # uncomment for logs
    command: [ 'postgres', '-c', 'log_statement=all' ]
    environment:
      POSTGRES_USER: 'master1'
      POSTGRES_PASSWORD: 'kermit'
      POSTGRES_DB: 'vend'

#  backend:
#    container_name: backend
#    build: ./backend
#    ports:
#      - '8080:8080'
#    environment:
#      API_PORT: '8080'
#      SQL_HOST: 'vend'
#      SQL_PORT: '5432'
#
#  frontend:
#    container_name: frontend
#    build: ./frontend
#    ports:
#      - '3000:3000'